title: Robot Studio
email: robopati@umich.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/robot-studio" # the subpath of your site, e.g. /blog
url: "https://elijahcantu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: null
github_username:  null
