- platform: LinkedIn
  url: https://www.linkedin.com/company/robot-studio-design/
  name: LinkedIn
  icon: fab fa-linkedin
- platform: GitHub
  url: https://github.com/studiorobot
  name: GitHub
  icon: fab fa-github

